// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PNET_Shop.Data;

#nullable disable

namespace PNET_Shop.Migrations
{
    [DbContext(typeof(ShopDbContext))]
    [Migration("20260516152837_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PNET_Shop.Models.Check", b =>
                {
                    b.Property<int>("CheckNo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("CHECK_NO");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CheckNo"));

                    b.Property<string>("CashierName")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("CASHIER_NAME");

                    b.Property<DateTime>("CheckDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("CHECK_DATE");

                    b.Property<double>("TotalSum")
                        .HasColumnType("float")
                        .HasColumnName("TOTAL_SUM");

                    b.HasKey("CheckNo");

                    b.ToTable("Checks", (string)null);
                });

            modelBuilder.Entity("PNET_Shop.Models.Department", b =>
                {
                    b.Property<decimal>("DeptId")
                        .HasColumnType("decimal(4,0)")
                        .HasColumnName("DEPT_ID");

                    b.Property<string>("Info")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("INFO");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("NAME");

                    b.HasKey("DeptId");

                    b.ToTable("Departments", (string)null);
                });

            modelBuilder.Entity("PNET_Shop.Models.Good", b =>
                {
                    b.Property<int>("GoodId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("GOOD_ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GoodId"));

                    b.Property<decimal>("DeptId")
                        .HasColumnType("decimal(4,0)")
                        .HasColumnName("DEPT_ID");

                    b.Property<string>("Description")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("DESCRIPTION");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("NAME");

                    b.Property<double>("Price")
                        .HasColumnType("float")
                        .HasColumnName("PRICE");

                    b.Property<string>("Producer")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("PRODUCER");

                    b.Property<int>("Quantity")
                        .HasColumnType("int")
                        .HasColumnName("QUANTITY");

                    b.Property<int>("SupplierId")
                        .HasColumnType("int")
                        .HasColumnName("SUPPLIER_ID");

                    b.HasKey("GoodId");

                    b.HasIndex("DeptId");

                    b.HasIndex("SupplierId");

                    b.ToTable("Goods", (string)null);
                });

            modelBuilder.Entity("PNET_Shop.Models.Sale", b =>
                {
                    b.Property<int>("SaleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("SALE_ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SaleId"));

                    b.Property<int>("CheckNo")
                        .HasColumnType("int")
                        .HasColumnName("CHECK_NO");

                    b.Property<DateTime>("DateSale")
                        .HasColumnType("datetime2")
                        .HasColumnName("DATE_SALE");

                    b.Property<int>("GoodId")
                        .HasColumnType("int")
                        .HasColumnName("GOOD_ID");

                    b.Property<int>("Quantity")
                        .HasColumnType("int")
                        .HasColumnName("QUANTITY");

                    b.HasKey("SaleId");

                    b.HasIndex("CheckNo");

                    b.HasIndex("GoodId");

                    b.ToTable("Sales", (string)null);
                });

            modelBuilder.Entity("PNET_Shop.Models.Supplier", b =>
                {
                    b.Property<int>("SupplierId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("SUPPLIER_ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SupplierId"));

                    b.Property<string>("Address")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)")
                        .HasColumnName("ADDRESS");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("NAME");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("PHONE");

                    b.HasKey("SupplierId");

                    b.ToTable("Suppliers", (string)null);
                });

            modelBuilder.Entity("PNET_Shop.Models.Good", b =>
                {
                    b.HasOne("PNET_Shop.Models.Department", "Department")
                        .WithMany("Goods")
                        .HasForeignKey("DeptId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PNET_Shop.Models.Supplier", "Supplier")
                        .WithMany("Goods")
                        .HasForeignKey("SupplierId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("PNET_Shop.Models.Sale", b =>
                {
                    b.HasOne("PNET_Shop.Models.Check", "Check")
                        .WithMany("Sales")
                        .HasForeignKey("CheckNo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PNET_Shop.Models.Good", "Good")
                        .WithMany("Sales")
                        .HasForeignKey("GoodId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Check");

                    b.Navigation("Good");
                });

            modelBuilder.Entity("PNET_Shop.Models.Check", b =>
                {
                    b.Navigation("Sales");
                });

            modelBuilder.Entity("PNET_Shop.Models.Department", b =>
                {
                    b.Navigation("Goods");
                });

            modelBuilder.Entity("PNET_Shop.Models.Good", b =>
                {
                    b.Navigation("Sales");
                });

            modelBuilder.Entity("PNET_Shop.Models.Supplier", b =>
                {
                    b.Navigation("Goods");
                });
#pragma warning restore 612, 618
        }
    }
}
